db:
  image: postgres
web:
  build: .
  dockerfile: Dockerfile
  environment:
    - VIRTUAL_HOST=testapp.dev
    - VIRTUAL_PORT=3000
    - HISTFILE=/app/.bash_history
  external_links:
  - shared_nginx_1:testapp.dev
  # expose:
  #   - 80
  volumes:
  - .:/app
  volumes_from:
    - bundler
  command: bundle exec rails s -b '0.0.0.0'
  links:
    - db 
    # - nginx:testapp.dev
bundler:
  image: ruby:2.1
  command: /bin/true
  volumes:
  - /usr/local/bundle

# nginx:
#   image: jwilder/nginx-proxy
#   ports:
#     - "80:80"
#   volumes:
#     - /var/run/docker.sock:/tmp/docker.sock:ro
#   restart: always

# dnsmasq:
#   image: andyshinn/dnsmasq
#   ports:
#     - "192.168.99.100:53:53/tcp"
#     - "192.168.99.100:53:53/udp"
#   cap_add:
#     - NET_ADMIN
#   command: --address=/dev/192.168.99.100
#   restart: always
